apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-user-deployment
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: backend-user
  template:
    metadata:
      labels:
        app: backend-user
    spec:
      containers:
        - name: backend-user
          image: namsangwon/studyhub-backend-user:0.0.1
          imagePullPolicy: Always
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: dev
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: /etc/config
              name: backend-user-config-volume
              readOnly: true
            - mountPath: /etc/secret/jwt
              name: jwt-secret-volume
              readOnly: true
            - mountPath: /etc/secret/mysql
              name: mysql-secret-volume
              readOnly: true
            - mountPath: /etc/secret/redis
              name: redis-secret-volume
              readOnly: true
      volumes:
        - name: backend-user-config-volume
          configMap:
            name: backend-user-config
            items:
              - key: application-dev.yml
                path: application-dev.yml
        - name: jwt-secret-volume
          secret:
            secretName: jwt-secret
            items:
              - key: application-jwt.yml
                path: application-jwt.yml
        - name: mysql-secret-volume
          secret:
            secretName: mysql-jdbc-secret
            items:
              - key: application-mysql.yml
                path: application-mysql.yml
        - name: redis-secret-volume
          secret:
            secretName: redis-secret
            items:
              - key: application-redis.yml
                path: application-redis.yml
