apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-user-deployment
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: backend-user
  template:
    metadata:
      labels:
        app: backend-user
    spec:
      containers:
        - name: backend-user
          image: namsangwon/backend-user:0.0.1
          imagePullPolicy: Always
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: dev
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: /etc/config
              name: backend-user-config-volume
              readOnly: true
            - mountPath: /etc/secret
              name: backend-user-secret-volume
              readOnly: true
      volumes:
        - name: backend-user-config-volume
          configMap:
            name: backend-user-config
            items:
              - key: application-dev.yml
                path: application-dev.yml
        - name: backend-user-secret-volume
          secret:
            secretName: backend-user-secret-volume
            items:
              - key: application-secret.yml
                path: application-secret.yml