spring:
  config:
    import:
      - file:/etc/config/application-dev.yml
      - file:/etc/secret/jwt/application-jwt.yml
      - file:/etc/secret/mysql/application-mysql.yml
      - file:/etc/secret/redis/application-redis.yml